-- 修正表/列 COMMENT 中文乱码（确保以 UTF-8 写入，执行时连接需使用 utf8mb4）
-- 若库中 COMMENT 已为乱码（如 çœŸå®žå§"å），本迁移会覆盖为正确中文

ALTER TABLE `ly_user` COMMENT='用户表';

ALTER TABLE `ly_user`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  MODIFY COLUMN `password` VARCHAR(255) NOT NULL COMMENT '密码',
  MODIFY COLUMN `real_name` VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
  MODIFY COLUMN `nickname` VARCHAR(50) DEFAULT NULL COMMENT '昵称（同步自 fa_staff.name）',
  MODIFY COLUMN `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  MODIFY COLUMN `mobile` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  MODIFY COLUMN `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像',
  MODIFY COLUMN `feishu_open_id` VARCHAR(64) DEFAULT NULL COMMENT '飞书 open_id，用于扫码登录',
  MODIFY COLUMN `union_id` VARCHAR(64) DEFAULT NULL COMMENT '开放平台 union_id，同一主体下多应用统一',
  MODIFY COLUMN `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间（同步自 fa_staff）',
  MODIFY COLUMN `department_id` BIGINT DEFAULT NULL COMMENT '部门ID',
  MODIFY COLUMN `entry_date` DATE DEFAULT NULL COMMENT '入职日期',
  MODIFY COLUMN `total_points` INT DEFAULT 0 COMMENT '累计积分',
  MODIFY COLUMN `study_time_long` INT DEFAULT 0 COMMENT '学习时长（分钟）（同步自 fa_staff）',
  MODIFY COLUMN `role` VARCHAR(20) DEFAULT 'student' COMMENT '角色：admin-管理员，teacher-教师，student-学员',
  MODIFY COLUMN `status` TINYINT DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
  MODIFY COLUMN `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` TINYINT DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除';
